version: '3.5'

services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    network_mode: "host"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    network_mode: "host"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_volume:/database

  aci_backend:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - db_volume:/app/database
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  db_volume: