version: '3.5'

services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    network_mode: "host"
    # ports:
    #   - 6379:6379

  aci_backend:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - db_volume:/app/database
    # ports:
    #   - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  db_volume: