version: '3.5'

services:
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    ports:
      - 6379:6379
    networks:
      - backend_net

  aci_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - db_volume:/app/database
    networks:
      - backend_net
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  db_volume:

networks:
  backend_net:
    driver: bridge