# Generated by Django 5.1.2 on 2024-10-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soar_endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soarinfo',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
