"""
Django settings for ACI_Backend project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "ACI_Backend.apps.MainBackendConfig",
    # 'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework_swagger",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "soar_endpoint",
    "siem_endpoint",
    "jobs_endpoint",
    "ai_system_endpoint",
    "ai_system_endpoint.task_generation",
    "ai_system_endpoint.automatic_investigation",
    "ai_system_endpoint.report_generation",
    "ai_system_endpoint.settings.apps.SettingsConfig",
    "dashboard_endpoint",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}

ROOT_URLCONF = "ACI_Backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", LOG_LEVEL).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s:%(lineno)d] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}

WSGI_APPLICATION = "ACI_Backend.wsgi.application"

# AI backend url
AI_BACKEND_URL = os.getenv("AI_BACKEND_URL")

# Secret API key for verifying the authenticity of the main backend
AI_BACKEND_API_KEY = os.getenv("AI_BACKEND_API_KEY")


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "db",
        "USER": "postgres",
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": "db",
        "PORT": 5432,
    }
}

# Job queue settings
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
REDIS_DB = 0
MAX_WORKERS = 5

WORKFLOW_QUEUE_KEY = os.getenv("WORKFLOW_QUEUE_KEY", "workflow:queue")
WORKFLOW_SLOT_KEY_PREFIX = os.getenv("WORKFLOW_SLOT_KEY_PREFIX", "workflow:slot")
WORKFLOW_SLOT_TTL_SECONDS = int(os.getenv("WORKFLOW_SLOT_TTL_SECONDS", "3600"))

# Maximum string length
MAXIMUM_STRING_LENGTH = int(os.getenv("MAXIMUM_STRING_LENGTH"))

# Page sizes
CASE_PAGE_SIZE = int(os.getenv("CASE_PAGE_SIZE"))

# Maximum concurrent agent (LLM) calls per investigation worker
AGENT_MAX_CONCURRENT_CALLS = int(os.getenv("AGENT_MAX_CONCURRENT_CALLS", "3"))

# SIEM schema retrieval refresh and cache settings
SIEM_SCHEMA_RETRIEVAL_INTERVAL_MINUTES = int(
    os.getenv("SIEM_SCHEMA_RETRIEVAL_INTERVAL_MINUTES", "10")
)
_DEFAULT_SIEM_SCHEMA_RETRIEVAL_CACHE_TTL_SECONDS = max(
    SIEM_SCHEMA_RETRIEVAL_INTERVAL_MINUTES * 120,
    600,
)
SIEM_SCHEMA_RETRIEVAL_CACHE_TTL_SECONDS = int(
    os.getenv(
        "SIEM_SCHEMA_RETRIEVAL_CACHE_TTL_SECONDS",
        str(_DEFAULT_SIEM_SCHEMA_RETRIEVAL_CACHE_TTL_SECONDS),
    )
)

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
